[package]
name = "grabber_core"
version = "0.0.0"
authors = ["Sam Sartor <me@samsartor.com>"]

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
uuid = { version = "0.6", features = ["serde", "v4"] }
url = { version="^1.7", features = ["serde"] }
failure = "0.1"
