[package]
name = "bag_derive"
version = "0.0.0"
authors = ["me@samsartor.com"]

[lib]
name = "bag_derive"
proc-macro = true

[dependencies]
proc-macro2 = "0.2"
quote = "0.4"
syn = { version = "0.12", features = ["visit"] }
bagger = { path = "../bagger" }
lazy_static = "1.0.0"
